Solve thses linear equations

5$x_1$ - $x_2$ + 2$x_3$ = 12 \\
3$x_1$ + 8$x_2$ - 2$x_3$ = -25 \\
$x_1$ + $x_2$ + $x_3$ = 6


In [63]:
#########################  GAUSS - SEIDEL METHOD 1  ############################


x1,x2,x3 = 0,0,0     #----------- Guess solution
print("  X1                              X2                               X3")

for _ in range(10):
    x1 = (x2 - 2*x3 + 12)/5
    x2 = (2*x3 - 3*x1 - 25)/8
    x3 = (6 - x1 - x2)
    print(f"{round(x1,3):->{5}}  {round(x2,3):->{30}}  {round(x3,3):->{30}}")


print('\n \n \n Final solution is: ',x1,x2,x3)

  X1                              X2                               X3
--2.4  -------------------------4.025  -------------------------7.625
-1.455  -------------------------0.673  -------------------------8.128
-0.986  -------------------------0.723  -------------------------7.709
-0.828  -------------------------0.887  -------------------------7.715
-0.864  -------------------------0.872  -------------------------7.736
-0.869  -------------------------0.865  -------------------------7.734
-0.867  -------------------------0.866  -------------------------7.733
-0.867  -------------------------0.867  -------------------------7.733
-0.867  -------------------------0.867  -------------------------7.733
-0.867  -------------------------0.867  -------------------------7.733

 
 
 Final solution is:  -0.8666713854856042 -0.8666622334289813 7.733333618914585


In [64]:
#########################  GAUSS - SEIDEL METHOD 2  ############################


M = np.array([[5,-1,2],[3,8,-2],[1,1,1]])
N = np.array([12,-25,6])
x = np.array([0,0,0])

L = np.tril(M)
U = M - L


print("    X1           X2           X3")

for loop in range(20):
    x = np.dot(np.linalg.inv(L), N - np.dot(U,x))
    print(x)
    


print('\n \n \n final solution of equations are (x1,x2,x3): \n',x)

    X1           X2           X3
[ 2.4   -4.025  7.625]
[-1.455    -0.673125  8.128125]
[-0.985875   -0.72326562  7.70914062]
[-0.82830937 -0.88709883  7.7154082 ]
[-0.86358305 -0.87230431  7.73588735]
[-0.8688158  -0.86522224  7.73403804]
[-0.86665966 -0.86649312  7.73315278]
[-0.86655974 -0.8667519   7.73331164]
[-0.86667504 -0.86666895  7.73334399]
[-0.86667139 -0.86666223  7.73333362]
[-0.86666589 -0.86666688  7.73333278]
[-0.86666649 -0.86666687  7.73333336]
[-0.86666672 -0.86666664  7.73333336]
[-0.86666667 -0.86666666  7.73333333]
[-0.86666666 -0.86666667  7.73333333]
[-0.86666667 -0.86666667  7.73333333]
[-0.86666667 -0.86666667  7.73333333]
[-0.86666667 -0.86666667  7.73333333]
[-0.86666667 -0.86666667  7.73333333]
[-0.86666667 -0.86666667  7.73333333]

 
 
 final solution of equations are (x1,x2,x3): 
 [-0.86666667 -0.86666667  7.73333333]
