In [41]:
import numpy as np
X = [5,10,15,20,25,30]
Y = [45,105,174,259,364,496]

D = [Y]
y = Y
for i in range(len(Y)-1):
    y = np.diff(y)
    D.append(y)

h = np.mean(np.diff(X))
print('h is',h)


############ Creating Forward Difference Table

for d in D:
    print(d)

h is 5.0
[45, 105, 174, 259, 364, 496]
[ 60  69  85 105 132]
[ 9 16 20 27]
[7 4 7]
[-3  3]
[6]


In [39]:
def term(t,n):
    coeff = 1
    for i in range(n):
        coeff = coeff * (t - i)
    return coeff/np.math.factorial(n)

x = float(input('Where do wnat to interpolate: '))
t = (x - X[0])/h    
print(t)

Where do wnat to interpolate: 18
2.6


In [42]:
sum = 0
for j in range(len(D)):
    sum = sum + term(t,j)*D[j][0]


print('So value of the function at {} is'.format(x),sum)

So value of the function at 18.0 is 222.826688


In [34]:
D[0][0]

45