##Forward Dfference Method:

In [2]:
import numpy as np

X = np.array([2,4,6,8,10])
Y = np.array([10,12.5,16,21.8,32.4])
D = []
y = Y
for i in range(len(Y)-1):
    y = np.diff(y)
    D.append(y)

h = np.mean(np.diff(X))
print('h is',h)


############ Creating Forward Difference Table
print(Y)
for d in D:
    print(d)


h is 2.0
[10.  12.5 16.  21.8 32.4]
[ 2.5  3.5  5.8 10.6]
[1.  2.3 4.8]
[1.3 2.5]
[1.2]


In [0]:
j = int(input("On which point do you want to calculate the differentiation? "))  ##enter 0
sum = 0

for i in range(len(D[j])):
    sum += ((D[i][0])/(i+1))*((-1)**i)

print((sum)/h)

On which point do you want to calculate the differentiation? 2
1.0


In [0]:
X = np.array([2,3,4,5,6])
Y = np.array([4,9,16,25,36])
D = []
y = Y
for i in range(len(Y)-1):
    y = np.diff(y)
    D.append(y)

h = np.mean(np.diff(X))
print('h is',h)

print(Y)
for d in D:
    print(d)
##############################################
j = int(input("On which point do you want to calculate the differentiation? ")) 
sum = 0

for i in range(len(D[j])):
    sum += ((D[i][0])/(i+1))*((-1)**i)

print((sum)/h)

h is 1.0
[ 4  9 16 25 36]
[ 5  7  9 11]
[2 2 2]
[0 0]
[0]
On which point do you want to calculate the differentiation? 0
4.0
