.......................................
<img class="irc_mi" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" onload="typeof google==='object'&amp;&amp;google.aft&amp;&amp;google.aft(this)" style="margin-top: 68px;" data-iml="1564848991379" alt="Image result for numpy" width="547" height="217">

In [0]:
import numpy as np
## You can use: import numpy
### import numpy as anything

1. ndarray is the way numpy stores data.
2. treats them as mathemetical objects
3. ndarray though created for numeric data types, supports string
4. ndarray supports one kind of datatype denoted as dtype
5. dtype is diffrent from python datatype and are more generic
6. if a 1D array then vector, if 2d array then matrix, if 3d array then tensor


In [0]:
x = [1,2,3,4]
print(x)


y = np.array([1,2,3,4])
print(y)

[1, 2, 3, 4]
[1 2 3 4]


In [0]:
x = [[1,2,3],[4,5,6],[7,8,9]]
print(x,'\n')                                          ## NOT a 3x3 matrix

y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)                                               ## It's a 3x3 matrix(2D)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
x = np.array([[1,2],[1.8,7.2]])
print(x, x.dtype)                              ### x.dtype gives the data type of array


y = np.array([[1,2],[2,7]])
print(y,y.dtype)

[[1.  2. ]
 [1.8 7.2]] float64
[[1 2]
 [2 7]] int64


# Numpy built-in methods
There are several methods to generate array in numpy arrays.Some of them are :


1.   np.arange()
2.   np.linspace()
3.   np.zeros()
4.   np.ones()
5.   np.identity()



###ARANGE

In [0]:
x = np.arange(0,10)     ## np.arange(START,STOP)
print(x)

y = np.arange(5,20,3)   ## np.arange(START,STOP,INTERVAL)
print(y)

# this method does not allow the STOP point. It breaks before STOP

[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17]


###LINSPACE

In [0]:
np.linspace(0,10,3)     ## np.linspace(START,STOP,NUMBER OF ELEMENTS)

array([ 0.,  5., 10.])

In [0]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

###LOGSPACE

In [0]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

###ZERO


In [0]:
np.zeros(5)        ## 1 dimensional array with all elements zero

array([0., 0., 0., 0., 0.])

In [0]:
np.zeros((5,5))    ## 2 dimensional 5x5 matrix with all elements zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

###ONE

In [0]:
np.ones(6)          ## 1 dimensional array with all elements zero

array([1., 1., 1., 1., 1., 1.])

In [0]:
np.ones((4,4))      ## 2 dimensional 5x5 matrix with all elements zero

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###IDENTITY MATRIX

In [0]:
np.identity(4)     ## 4x4 Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.eye(3)          ## 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#RANDOM ARRAYs
numpy has a lots of ways to generate random number arrays.

###np.random.rand(n)
This creates n random numbers with a distribution between [0,1]. It creates an uniform distribution.


In [0]:
np.random.rand(5)               ##  1D array wiith random numbers between 0 to 1

array([0.97969171, 0.2293302 , 0.13390578, 0.78463268, 0.69234734])

In [0]:
np.random.rand(4,4)             ##  2D 4x4 array wiith random numbers between 0 to 1

array([[0.42706213, 0.31466928, 0.26887176, 0.52135146],
       [0.52331112, 0.77782231, 0.12167404, 0.73107891],
       [0.49235278, 0.79528163, 0.99896807, 0.91171545],
       [0.43651322, 0.62234127, 0.54944355, 0.13357183]])

###np.random.randn(n)
Return a sample (n elements) from the "standard normal" distribution. Unlike rand which is uniform.

In [0]:
np.random.randn(4)                ## follows normal distributions around 0

array([-0.23565432,  1.36332099, -1.02298001,  1.12896532])

In [0]:
np.random.randn(3,3)              ## follows normal distributions around 0

array([[ 1.01812914, -1.54091039, -0.38323974],
       [ 0.66675669,  0.0067574 ,  0.3039311 ],
       [-0.06475376,  0.76092319, -1.79236527]])

###np.random.randint(n)

In [0]:
np.random.randint(8)           ## gives a random integer within a range from 0

3

In [0]:
np.random.randint(20,25)        ## gives random number within a defined range

23

In [0]:
np.random.randint(20,25,10)     ## np.random.randint(START,STOP, NO OF ELEMENTS)

array([22, 20, 23, 24, 21, 21, 24, 23, 23, 23])

#Array Manipulation

In [0]:
x = np.array([[3,5,1],[2,9,2],[8,7,3],[1,4,9]])
x

array([[3, 5, 1],
       [2, 9, 2],
       [8, 7, 3],
       [1, 4, 9]])

In [0]:
x.shape      ## '.shape' gives the (rows,columns)

(4, 3)

In [0]:
x.size       ## '.size' gives the number of elements in an array

12

In [0]:
x.ndim       ## '.ndim' gives the dimension of the array

2

In [0]:
x.T          ## '.T' gives the transpose of the arraay (matrix)

array([[3, 2, 8, 1],
       [5, 9, 7, 4],
       [1, 2, 3, 9]])

In [0]:
x.reshape(6,2)     ## 4x3 array is converted into 6x2 array. Total number of element is 12

array([[3, 5],
       [1, 2],
       [9, 2],
       [8, 7],
       [3, 1],
       [4, 9]])

In [0]:
x                 ## '.reshape()' does not change the shape of acctual array

array([[3, 5, 1],
       [2, 9, 2],
       [8, 7, 3],
       [1, 4, 9]])

In [0]:
x.reshape(3,4).shape 
 ## In this line of code 1st we changed the dimension from 4x3 to 3x4,
 ## and then printed the shape of modified x

(3, 4)

In [0]:
x.ravel()        ## converts the array into 1D array

array([3, 5, 1, 2, 9, 2, 8, 7, 3, 1, 4, 9])

In [0]:
x.flatten()      ## converts the array into 1D array

array([3, 5, 1, 2, 9, 2, 8, 7, 3, 1, 4, 9])

#Array Info

In [0]:
x

array([[3, 5, 1],
       [2, 9, 2],
       [8, 7, 3],
       [1, 4, 9]])

In [0]:
x.sum()

54

In [0]:
x.max()          ## Gives the higest element of the array

9

In [0]:
x.min()          ## Gives the lowest element of the array

1

In [0]:
x.argmin()

2

In [0]:
x.argmax()

4

In [0]:
x.dtype          ## Gives data types of the elements

dtype('int64')

#Copying an ARRAY

In [0]:
y = x.copy()     ## '.copy' makes copy of primary array 
y

array([[3, 5, 1],
       [2, 9, 2],
       [8, 7, 3],
       [1, 4, 9]])

#Array Indexing

In [0]:
## 1D array indexing

x = np.random.randint(5,50,10)
print(x)                       


print(x[6],'is the 6th element.')      ##This indexing style is similar to list indexing

[38 38 15 20 41 35 36 46 12 25]
36 is the 6th element.


In [0]:
## 2D array indexing

x = np.random.randint(0,50,9)
print(x,'\n\n')

y = x.reshape(3,3)
print(y)                       ## It's just a 3x3 aray with random integers


[40 44 48  7  5 36 43 20 29] 


[[40 44 48]
 [ 7  5 36]
 [43 20 29]]


In [0]:
print(y[1],'is the first row')
print(y[:,2],'is the 2nd column. It is expressed in row format.') #':' means all row elements
print(y[1,2],'is the element of 2nd row and 3rd column. ')

[ 7  5 36] is the first row
[48 36 29] is the 2nd column. It is expressed in row format.
36 is the element of 2nd row and 3rd column. 


#Array Selection & Slicing

###1D array slicing

In [0]:
x = np.random.randint(0,20,10)
print(x)

[18 11  9  3 19  6  9  1 15 19]


In [0]:
x[2:7]           ## 1D array selection and slicing from 2nd element to (7-1)=6th element

array([ 9,  3, 19,  6,  9])

###2D array Slicing

In [0]:
y       ## is our previously stored 2D y matrix

array([[40, 44, 48],
       [ 7,  5, 36],
       [43, 20, 29]])

In [0]:
y[1:]   ##  Eleminates the 1st row

array([[ 7,  5, 36],
       [43, 20, 29]])

In [0]:
y[:-1]  ## Eleminates last row

array([[40, 44, 48],
       [ 7,  5, 36]])

In [0]:
y[1:-1] ## Eleminates the 1st and last rows

array([[ 7,  5, 36]])

In [0]:
y[:,1:]    ## Eleminates the 1sst column

array([[44, 48],
       [ 5, 36],
       [20, 29]])

In [0]:
y[:,:-1]       ## Eleminates the last column

array([[40, 44],
       [ 7,  5],
       [43, 20]])

In [0]:
y[0]    ## gives 1st row, y[2] will give 3rd row

array([40, 44, 48])

In [0]:
y[:,1]  ## gives 1st column. Expressed in a row format

array([44,  5, 20])

In [0]:
y[1:3,1:3]  #new sliced sub 2x2 matrix

array([[ 5, 36],
       [20, 29]])

#Boolean properties

In [0]:
x = np.random.randint(1,20,10)
x

array([ 8, 15, 13, 10,  1, 15, 18,  6,  1, 15])

In [0]:
x>5        ## Validates the condition and prints the statement of validation

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True])

In [0]:
x[x>5]     ## Array modification under boolean condition

array([ 8, 15, 13, 10, 15, 18,  6, 15])

#Numpy Operations

In [0]:
my_list1 = [2,3,4]       
my_list2 = [5,6,7]


print(2*my_list1,'List multiplication')          ## python list multiplication works as concatination
print(my_list1 + my_list2,'List addiition')      ## addition is also concatination


[2, 3, 4, 2, 3, 4] List multiplication
[2, 3, 4, 5, 6, 7] List addiition


In [0]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(2*x,'    Numpy 1D array Scalar Multiplication')
print(x+y,'Numpy 1D array addition')
print(y-x,'    Numpy 1D array Subtraction')
print(x*y,'Numpy array Multiplication: Element wise multiplication')
print(x**3,'Numpy cubic operation')

[2 4 6 8]     Numpy 1D array Scalar Multiplication
[ 6  8 10 12] Numpy 1D array addition
[4 4 4 4]     Numpy 1D array Subtraction
[ 5 12 21 32] Numpy array Multiplication: Element wise multiplication
[ 1  8 27 64] Numpy cubic operation


###Mathematical Universal Operations

In [0]:
print(np.sin(x),'              SinX')
print(np.cos(x),'              CosX')
print(np.sqrt(x),'            Square root')
print(np.log(x),'             Logarithm')
print(np.exp(x),'         Exponential')

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]               SinX
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]               CosX
[1.         1.41421356 1.73205081 2.        ]             Square root
[0.         0.69314718 1.09861229 1.38629436]              Logarithm
[ 2.71828183  7.3890561  20.08553692 54.59815003]          Exponential


###Matrix Operations(2D)

In [0]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x,'x matrix\n')
print(y,'y matrix')

[[1 2]
 [3 4]] x matrix

[[5 6]
 [7 8]] y matrix


In [0]:
x+y      ## Matrix Addition

array([[ 6,  8],
       [10, 12]])

In [0]:
x@y      ## Scalar Multiplication(dot product)

array([[19, 22],
       [43, 50]])

In [0]:
x.dot(y) ## Scalar multiplication(Dot product)    **** not DOT product

array([[19, 22],
       [43, 50]])

In [0]:
x*y      ## Elementwise multiplication

array([[ 5, 12],
       [21, 32]])

In [0]:
print(5*x)

[[ 5 10]
 [15 20]]


#Numpy Stacking

#Statistical Functions

In [0]:
a = np.random.randint(0,10,50)
print(a)


[1 8 7 3 7 9 9 3 1 8 6 1 5 4 8 7 8 6 3 6 9 8 1 6 2 9 1 4 2 8 9 3 3 1 5 7 6
 3 5 4 3 6 1 2 7 8 7 1 3 2]


In [0]:
print(np.median(a),'Statistical Median')
print(np.mean(a),'Statistical Mean')
print(np.average(a),'Average')
print(np.std(a),'Standard deviation')
print(np.var(a),'Variance')

5.0 Statistical Median
4.92 Statistical Mean
4.92 Average
2.726462910072316 Standard deviation
7.4336 Variance


In [0]:
np.histogram(a)

(array([8, 4, 8, 3, 0, 3, 6, 6, 7, 5]),
 array([1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2, 9. ]))

#Bitwise Operation

In [0]:
a = np.array([0,1,1,0])
b = np.array([0,0,1,1])
print(np.bitwise_and(a,b),'    Bitwise AND')
print(np.bitwise_or(a,b), '    Bitwise OR')
print(np.bitwise_xor(a,b), '    Bitwise XOR')
print(np.bitwise_not(a), 'Bitwise NOT is a unary operation')

[0 0 1 0]     Bitwise AND
[0 1 1 1]     Bitwise OR
[0 1 0 1]     Bitwise XOR
[-1 -2 -2 -1] Bitwise NOT is a unary operation
