In [0]:
import numpy as np

In [0]:
I = np.eye(3,3)
A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
C = np.array([[9,2,3],[6,5,6],[2,8,9]])
D = np.array([5])
E = np.array([1,2,3])
F = np.array([[4],[5],[6]])
G = np.array(4)

In [9]:
# Matrix Rank

print(np.linalg.matrix_rank(A),'rank is of A ')
print(np.linalg.matrix_rank(B),'rank is of B ')
print(np.linalg.matrix_rank(C),'rank is of C ')
print(np.linalg.matrix_rank(I),'rank is of I ')
print(np.linalg.matrix_rank(D),'rank is of D ')
print(np.linalg.matrix_rank(E),'rank is of E ')
print(np.linalg.matrix_rank(F),'rank is of F ')
print(np.linalg.matrix_rank(G),'rank is of G ')

2 rank is of A 
2 rank is of B 
3 rank is of C 
3 rank is of I 
1 rank is of D 
1 rank is of E 
1 rank is of F 
1 rank is of G 


In [10]:
# Matrix Trace

print('Trace of matrix A id {}'.format(np.trace(A)))

Trace of matrix A id 7


In [11]:
# Determinant

print('Determinant of A is {}'.format(np.linalg.det(C)))

Determinant of A is 3.00000000000005


In [12]:
# Matrix power

np.linalg.matrix_power(C,3)

array([[1335,  986, 1203],
       [1578, 1433, 1716],
       [1722, 1828, 2163]])

In [13]:
# Matrix Inverse

np.linalg.inv(C)

array([[ -1.        ,   2.        ,  -1.        ],
       [-14.        ,  25.        , -12.        ],
       [ 12.66666667, -22.66666667,  11.        ]])

## Eigen Values and Eigen Vectors

In [21]:
# Eigen Values

x,y = np.linalg.eigh(C)   # for symmetric matrices
print(x,y)

[-2.48064048  7.07397648 18.406664  ] [[-0.33113193  0.79243543 -0.51224773]
 [ 0.80025107 -0.05179051 -0.59742445]
 [-0.49994987 -0.60775311 -0.61699781]]


In [0]:
print(x)   # Here are the eigen values

[-2.48064048  7.07397648 18.406664  ]


In [15]:
print(y)   #  Here are the eigen vectors

[[-0.33113193  0.79243543 -0.51224773]
 [ 0.80025107 -0.05179051 -0.59742445]
 [-0.49994987 -0.60775311 -0.61699781]]


In [16]:
np.linalg.eigvals(C)   # -------------Eigen values only

array([16.73729324,  6.23395448,  0.02875229])

In [17]:
q = np.array([[1,2],[3,4]])
V,x = np.linalg.eig(q)
print(V,'eigen vectors')
print(x,'eigen values')

[-0.37228132  5.37228132] eigen vectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]] eigen values


#### linalg.eigvalsh(a[, UPLO]) 	Compute the eigenvalues of a complex Hermitian or real symmetric matrix.

In [18]:
#### Product

m = np.array([1,2,3])
n = np.array([4,5,6])
print(np.vdot(m,n))
print(np.inner(m,n))
print(np.matmul(m,n))
print(np.outer(m,n))
print(np.kron(m,n))
#print(np.tensordot(m))

32
32
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[ 4  5  6  8 10 12 12 15 18]


In [19]:
##   Solving linear equations
##    x + 2y = 8
##   3x + 4y = 18 

M = np.array([[1,2],[3,4]])
N = np.array([8,18])

print('Solution of this linear equation is: ',np.linalg.solve(M,N))


Solution of this linear equation is:  [2. 3.]


# Normalization

In [20]:
p = np.array([1,2,3])
print(np.linalg.norm(p,1))  #------ L1 norm
print(np.linalg.norm(p,2))  #------ L2 norm
print(np.linalg.norm(p,3))  #------ L3 norm

6.0
3.7416573867739413
3.3019272488946263
