In [0]:
import numpy as np

In [0]:
I = np.eye(3,3)
A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
C = np.array([[9,2,3],[6,5,6],[2,8,9]])
D = np.array([5])
E = np.array([1,2,3])
F = np.array([[4],[5],[6]])
G = np.array(4)

### Matrix Rank

In [0]:
print(np.linalg.matrix_rank(A),'rank is of A ')
print(np.linalg.matrix_rank(B),'rank is of B ')
print(np.linalg.matrix_rank(C),'rank is of C ')
print(np.linalg.matrix_rank(I),'rank is of I ')
print(np.linalg.matrix_rank(D),'rank is of D ')
print(np.linalg.matrix_rank(E),'rank is of E ')
print(np.linalg.matrix_rank(F),'rank is of F ')
print(np.linalg.matrix_rank(G),'rank is of G ')

2 rank is of A 
2 rank is of B 
3 rank is of C 
3 rank is of I 
1 rank is of D 
1 rank is of E 
1 rank is of F 
1 rank is of G 


### Matrix Trace

In [0]:
print('Trace of matrix A id {}'.format(np.trace(A)))

Trace of matrix A id 7


### Determinant

In [0]:
print('Determinant of A is {}'.format(np.linalg.det(C)))

Determinant of A is 3.00000000000005


### Matrix power

In [0]:
np.linalg.matrix_power(C,3)

array([[1335,  986, 1203],
       [1578, 1433, 1716],
       [1722, 1828, 2163]])

### Matrix Inverse

In [0]:
np.linalg.inv(C)

array([[ -1.        ,   2.        ,  -1.        ],
       [-14.        ,  25.        , -12.        ],
       [ 12.66666667, -22.66666667,  11.        ]])

### Eigen Values and Eigen Vectors

In [6]:
x,y = np.linalg.eig(C)   # for symmetric matrices
print('Eigen values are: ',x,'\n \n Eigen vectors are \n',y)

Eigen values are:  [16.73729324  6.23395448  0.02875229] 
 
 Eigen vectors are 
 [[-0.42074435 -0.71218878 -0.06004531]
 [-0.57413373 -0.06366878 -0.73831921]
 [-0.70238498  0.69909472  0.67177326]]


In [0]:
print('Here are the eigen values \n',x)   # Here are the eigen values

Here are the eigen values 
 [-2.48064048  7.07397648 18.406664  ]


In [0]:
print('Here are the eigen vectors: \n',y)   #  Here are the eigen vectors

Here are the eigen vectors: 
 [[-0.33113193  0.79243543 -0.51224773]
 [ 0.80025107 -0.05179051 -0.59742445]
 [-0.49994987 -0.60775311 -0.61699781]]


In [0]:
q = np.array([[1,2],[3,4]])
V,x = np.linalg.eig(q)

print(x,'eigen vectors')
print(V,'eigen values')

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]] eigen vectors
[-0.37228132  5.37228132] eigen values


#### Product: Matrix Multiplication

In [0]:
m = np.array([1,2,3])
n = np.array([4,5,6])


print('Dot product is: ',np.vdot(m,n))
print('Cross product is: ',np.cross(m,n))
print('Inner Product is: ',np.inner(m,n))
print('Normal Matrix multiplication: ',np.matmul(m,n))
print('Outer Product is: \n',np.outer(m,n))
print('Kronacker product is: ',np.kron(m,n))

#print(np.tensordot(m))

Dot product is:  32
Cross product is:  [-3  6 -3]
Inner Product is:  32
Normal Matrix multiplication:  32
Outer Product is: 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Kronacker product is:  [ 4  5  6  8 10 12 12 15 18]


###   Solving linear equations
x + 2y = 8    and     3x + 4y = 18 

In [0]:
##   Solving linear equations
##    x + 2y = 8
##   3x + 4y = 18 

M = np.array([[1,2],[3,4]])
N = np.array([8,18])

print('Solution of this linear equation is: ',np.linalg.solve(M,N))


Solution of this linear equation is:  [2. 3.]


### Normalization

In [0]:
p = np.array([1,2,3])
print(np.linalg.norm(p,1))  #------ L1 norm
print(np.linalg.norm(p,2))  #------ L2 norm (Eucledian Length)
print(np.linalg.norm(p,3))  #------ L3 norm

6.0
3.7416573867739413
3.3019272488946263


### Diagonalizing a matrix

In [0]:
A = np.array([[1,4],[2,3]])    #---------Diagonalize A

B,C = np.linalg.eig(A)
# Here C is matrix containing eigen vectors
P = C
P_inv = np.linalg.inv(C)
D = np.matmul(P_inv,np.matmul(A,P))


print('Eigen values are: ',B)
print('\n \nThe result of diagonalization is: \n',D)

Eigen values are:  [-1.  5.]

 
The result of diagonalization is: 
 [[-1.00000000e+00  6.78974479e-16]
 [-5.38018942e-17  5.00000000e+00]]
